Update sync.yml

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -5,7 +5,7 @@ permissions:
 
 on:
   schedule:
-    - cron: "0 0 */15 * *" # 每 15 天一次
+    - cron: "0 0 * * *"  # 每天 00:00 运行
   workflow_dispatch:
 
 jobs:
@@ -15,24 +15,26 @@ jobs:
     if: ${{ github.event.repository.fork }}
 
     steps:
-      # Step 1: Checkout target repo
+      # Step 1: run a standard checkout action
       - name: Checkout target repo
         uses: actions/checkout@v3
 
-      # Step 2: Add upstream repository and fetch changes
-      - name: Add upstream repository
-        run: |
-          git remote add upstream https://github.com/cmliu/WorkerVless2sub.git
-          git fetch upstream main
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
+        with:
+          upstream_sync_repo: cmliu/WorkerVless2sub
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-      # Step 3: Merge changes, excluding workflows
-      - name: Merge upstream changes
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
         run: |
-          git merge --no-commit --no-ff upstream/main
-          git restore --staged .github/workflows
-          git commit -m "Sync from upstream, excluding workflows"
-      
-      # Step 4: Push changes to the fork repository
-      - name: Push changes
-        run: |
-          git push origin main
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
